= PBINFO_Utils
NonNullDinu
v1.0, 2019-12-16
:toc: right
:icons: font

== Descriere
O simpla interfata de https://en.wikipedia.org/wiki/Web_scraping[web scraping] pentru https://pbinfo.ro[pbinfo]
(in mare parte pentru teme) scrisa in Python 3.

WARNING: Aceasta interfata nu a fost scrisa de catre creatorii site-ului Pbinfo

== Configurare
=== Linux
Rulati in bash:
[source,bash]
----
./configure.sh
----

=== Windows
Deschideti un editor si completati cu numele de utilizator si parola dumneavoastra
[source,ini]
----
[pbinfo]
user=****
parola=****
----
Salvati acest fisier langa sursele .py cu denumirea __user_data.ini__

NOTE: In absenta acestui fisier, datele de logare vor fi cerute de catre program cand este rulat


== Cum se ruleaza programele?
Simplu! Navigati la sursele .py si apelati interpretorul python
[source,bash]
----
python <program>.py
----
Unde <program> este unul dintre urmatoarele::

    download_sources:::
        Descarca toate sursele trimise dintr-o tema intr-un folder(doar ultimele trimise vor ramane salvate).

    locate_completed_problems:::
        Cauta intr-o tema toate problemele deja rezolvate, construieste si afiseaza link-uri pentru pagina fiecarei probleme in care editorul are prima sursa de 100p gasita.
        Link-urile sunt de forma:

        https://www.pbinfo.ro/probleme/id/nume/?id_sursa=********#a_editor

    prob_statement:::
        Cauta o problema dupa datele de intrare si scrie pe ecran HTML-ul relevant enuntului in pagina.

Trebuie sa furnizati toate datele cerute de program
